FROM python:3.12


COPY requirements.txt /app/
WORKDIR /app

RUN pip install -r requirements.txt

ENV PYTHONPATH=/app

COPY . .

EXPOSE 8080

CMD ["uvicorn", "app.api_main:app", "--host", "0.0.0.0", "--port", "8080"]