version: "3.8"
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile_bot
    container_name: keriabot
  web:
    build:
      context: .
      dockerfile: Dockerfile_app
    ports:
      - "8000:8080"
    container_name: keriabot_api